package example

import tyrian.next.*
import scalajs.js

/** Events related to clock functionality. The `Tick` event is generated by the watcher and carries
  * the current time to update the clock display.
  */
//```scala
enum ClockEvent extends GlobalMsg:
  case Tick(newTime: js.Date)
//```
